import requests
import json

# URL to send the POST request to
post_req_url = "https://wabi-north-europe-h-primary-redirect.analysis.windows.net/export/xlsx"

# Authorization token
auth_token = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCIsImtpZCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvOTdjMzI1ZDAtNGNjYi00M2YzLTg1OGMtYTBhYjA1NzQxOTg3LyIsImlhdCI6MTcxNjExMTI4MywibmJmIjoxNzE2MTExMjgzLCJleHAiOjE3MTYxMTY1MDIsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84V0FBQUFOK0x6T2R0b1krOEozazdDMFE0SlBiRFRKZnltWWRVREIwU3J5OElnSFIzL1RkRG9wMmE0dG5qZVhDb3hnYkIzQzNzaW4zd1RPSHBsTHcxUzkwZ2JvU3JwNzlBaEp5Skl5ZEtFc0hQQkl5ND0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiODcxYzAxMGYtNWU2MS00ZmIxLTgzYWMtOTg2MTBhN2U5MTEwIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJCZXJnYW4iLCJnaXZlbl9uYW1lIjoiS2V2aW4gTWF0aGlhcyIsImlwYWRkciI6Ijg5LjguMjUzLjIxNyIsIm5hbWUiOiJLZXZpbiBNYXRoaWFzIEJlcmdhbiIsIm9pZCI6ImIxMTBkMTA0LTc2YTQtNDk3MS05OGI1LTA5Mzg4OGY3Y2M5MSIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0xMDgzMjI4OTg0LTMwODI2OTQzMTUtMjkzNjQ0MDktMjI1MTM1IiwicHVpZCI6IjEwMDMyMDAwOTk2RERGMzkiLCJyaCI6IjAuQVVjQTBDWERsOHRNODBPRmpLQ3JCWFFaaHdrQUFBQUFBQUFBd0FBQUFBQUFBQUFOQWVzLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6Ik4tT3pIMXhPWDlsM3dNYXFnWDl3V2xOcTM1WnN0YmVpMUlIbTQ3OEFjM3ciLCJ0aWQiOiI5N2MzMjVkMC00Y2NiLTQzZjMtODU4Yy1hMGFiMDU3NDE5ODciLCJ1bmlxdWVfbmFtZSI6Ilk1NTg3NzFAZW0uYWJnLmNvbSIsInVwbiI6Ilk1NTg3NzFAZW0uYWJnLmNvbSIsInV0aSI6IkFmWEVXTEN5djBhczdYT0VMcXdXQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdfQ.DU2rw8j3SoYDwO74CnaM6q0A5m0SzUd11rm5_p9SHmZGx1tMGJkYObqqtqij1qqx6MVYgFQGIvw7Vf0OKNiaTpB1I7cD0weVQW3BQ1PpqZRpoUzs23NQIi2wPhflDFahf4ankSMJ5uYhUxAJ1a87XW2wt9ZtOUKTcYR48fx_F01XBkAWtLucOkRE3oTsA7gyxBQsGCjLELCbE_P2-TRZHAt-4DQn-YoRB74b127KQwlXLNTua2zf7cuNrjagnRvqecWkNqemrrZsQSh5Px2vpPaBP4CzmMmDVlQJZ15c79dCxdtWjhuW4tczZcXeYKid2y098Do_dy4cc_u-4ZzKtg"

# Headers for the POST request
headers = {
    "Authorization": auth_token,
}

# Data is located in a local file called "postReqJson.json"
with open("./public/postReqJson.json", "r") as f:
    data = json.load(f)

# Send the POST request
response = requests.post(post_req_url, headers=headers, json=data)

# Print the status code of the response
print(response.status_code)

if (response.status_code != 200):
    print("Error: ", response.text)
    exit()

# Save the response as a file called "data.xlsx"
# Marking the data with the current date and time 
with open("./public/data.xlsx", "wb") as f:
    f.write(response.content)

print("File saved as data.xlsx")