import requests
import json

# URL to send the POST request to
post_req_url = "https://wabi-north-europe-h-primary-redirect.analysis.windows.net/export/xlsx"

# Authorization token
auth_token = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCIsImtpZCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvOTdjMzI1ZDAtNGNjYi00M2YzLTg1OGMtYTBhYjA1NzQxOTg3LyIsImlhdCI6MTcxNTc4MTM2MCwibmJmIjoxNzE1NzgxMzYwLCJleHAiOjE3MTU3ODU4NTcsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84V0FBQUE4M0JnK3pyeGRzR1kydHJQT3BkRWhaTWtJQm42TUp0cU5VTnlaMVo0U1BDMTZSYjJKdUY1QkNMVkRvWmNMVGhQMUNJcmE0bXl3NGhjSGZUalU5cEpTRFJkVEVWdWxWeUVRdHFaY204SWRlYz0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiODcxYzAxMGYtNWU2MS00ZmIxLTgzYWMtOTg2MTBhN2U5MTEwIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJCZXJnYW4iLCJnaXZlbl9uYW1lIjoiS2V2aW4gTWF0aGlhcyIsImlwYWRkciI6Ijg5LjguMjUyLjE1MCIsIm5hbWUiOiJLZXZpbiBNYXRoaWFzIEJlcmdhbiIsIm9pZCI6ImIxMTBkMTA0LTc2YTQtNDk3MS05OGI1LTA5Mzg4OGY3Y2M5MSIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0xMDgzMjI4OTg0LTMwODI2OTQzMTUtMjkzNjQ0MDktMjI1MTM1IiwicHVpZCI6IjEwMDMyMDAwOTk2RERGMzkiLCJyaCI6IjAuQVVjQTBDWERsOHRNODBPRmpLQ3JCWFFaaHdrQUFBQUFBQUFBd0FBQUFBQUFBQUFOQWVzLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6Ik4tT3pIMXhPWDlsM3dNYXFnWDl3V2xOcTM1WnN0YmVpMUlIbTQ3OEFjM3ciLCJ0aWQiOiI5N2MzMjVkMC00Y2NiLTQzZjMtODU4Yy1hMGFiMDU3NDE5ODciLCJ1bmlxdWVfbmFtZSI6Ilk1NTg3NzFAZW0uYWJnLmNvbSIsInVwbiI6Ilk1NTg3NzFAZW0uYWJnLmNvbSIsInV0aSI6IkhEV1M1QjhrQUVtX0hKLXBqUTFOQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdfQ.OwLZ1cQ-gsaywoICESe9XMkfKQZRp0nVYu6LQUugKXhaX7xzs7xaEto3U-dEmKTd86BnvsYn8D-Ciwxt9oIL2f-8dx41MSxXqlPQbzJwS8ACiAxB-L9YZh-cm-X6HOPr4Te5glIBc0IreoAEyzsFDSL3mC4-PAoVEETath1QqtMNLO2JjHJQ8SanFFiI6tmwKkdaA7mV3P7MNEnv-tmkou13pTjGhODXKtgjN8pkLDUQdMPHyrZHC1tUrEhboInTeZMYTBbOk2T4aZrkonXKuhdYv1dUCKTOIWlQsYSsDK60BGA8H3QIc-SkUfyiZdo6LSyRz1_lwNIPwWV5wPO3VA"

# Headers for the POST request
headers = {
    "Authorization": auth_token,
}

# Data is located in a local file called "postReqJson.json"
with open("./postReqJson.json", "r") as f:
    data = json.load(f)

# Send the POST request
response = requests.post(post_req_url, headers=headers, json=data)

# Print the status code of the response
print(response.status_code)

if (response.status_code != 200):
    print("Error: ", response.text)
    exit()

# Save the response as a file called "data.xlsx"
# Marking the data with the current date and time 
with open("./data.xlsx", "wb") as f:
    f.write(response.content)

print("File saved as data.xlsx")